### ISSUE TITLE
How to map event to RGB pixel by pixel in BS-ERGB

### ISSUE THREAD

**Issue by hewh16** [uzh-rpg/timelens-pp#2]
Hi~

Thanks for your nice work! I have some questions about processing raw event data.
In BS-ERGB dataset, I found the x, y in raw event data is 60000+ or 20000+, much greater than the resolution of RGB image. Could you provide the correspondence of spatial coordinates between event data and image? So that I can map event to RGB pixel by pixel.

Thanks :)

**Comment by DachunKai** [comment]
> Hi~
> 
> Thanks for your nice work! I have some questions about processing raw event data. In BS-ERGB dataset, I found the x, y in raw event data is 60000+ or 20000+, much greater than the resolution of RGB image. Could you provide the correspondence of spatial coordinates between event data and image? So that I can map event to RGB pixel by pixel.
> 
> Thanks :)

Hi, i guess we should divide the x,y by 32, but I don't assure the reason.

And,  in the paper, author mentions that "The dataset is divided into 78training scenes". But I only see 49 scenes in 3_TRAINING folder, what about you?

**Comment by DachunKai** [comment]
> Hi~
> 
> Thanks for your nice work! I have some questions about processing raw event data. In BS-ERGB dataset, I found the x, y in raw event data is 60000+ or 20000+, much greater than the resolution of RGB image. Could you provide the correspondence of spatial coordinates between event data and image? So that I can map event to RGB pixel by pixel.
> 
> Thanks :)

Do you solve it? How to use such dataset?

**Comment by ahmetakman** [comment]
Is anyone found out how to use the event side of this dataset?

**Comment by XiangZ-0** [comment]
I encounter the same problem, does anyone know how to resolve this? Thanks in advance.

**Comment by yunfanLu** [comment]
Encountered the same problem? This is really confusing.

**Comment by wefvdge** [comment]
It‘s been almost one year and this problem still remains unresolved? It's really confusing!

**Comment by hewh16** [comment]
Hi, guys. Sorry I didn't reply before. I have already resolved this problem. You can find problems by visualizing the data. There is only several events near the right edge of the event image, which is caused by horizontal coordinate data overflow. Hoping it helps.

**Comment by DachunKai** [comment]
> Hi, guys. Sorry I didn't reply before. I have already resolved this problem. You can find problems by visualizing the data. There is only several events near the right edge of the event image, which is caused by horizontal coordinate data overflow. Hoping it helps.

Hi，Could you share the minimal code example?

**Comment by leon-w** [comment]
After some experiments, i ended with this. I visually checked some examples and the events seem to align with the images but take it with a grain of salt and confirm for yourself that it actually works.

```python
# assume we have the raw event data in the arrays x, y, t, p
w, h = 970, 625

# convert to signed integers
x = x.astype(np.int16)
y = y.astype(np.int16)

# THE FOLLOWING 'MAGIC NUMBERS' ARE JUST GUESSES!
# VISUALLY THE EVENTS SEEM TO BE ALIGNED WITH THE IMAGE
# BUT THIS IS NOT CONFIRMED BY THE DATASET AUTHORS!
# VALIDATE FOR YOURSELF BEFORE USING THIS!
max_val_allowed_x = round((w / h) * 20_000)
max_val_allowed_y = 20_000

# filter out events that are outside the image
mask = (x >= 0) & (x <= max_val_allowed_x) & (y >= 0) & (y <= max_val_allowed_y)

x = x[mask]
y = y[mask]
t = t[mask]
p = p[mask]

# convert the events to pixel coordinates
x = np.round(x / max_val_allowed_x * w).astype(np.int16)
y = np.round(y / max_val_allowed_y * h).astype(np.int16)
```

**Comment by ercanburak** [comment]
Anyone still trying to figure this out can also check the code in [EVREAL tools](https://github.com/ercanburak/EVREAL/tree/main/tools). Here, we scale the x and y coordinates of events to the correct range and fix overflow issues. After that conversion, the visualizations of events align with the images (at least to a certain degree.)
