### ISSUE TITLE
Do you really contribute a dataset?

### ISSUE THREAD

**Issue by DachunKai** [uzh-rpg/timelens-pp#5]
In your paper, you saied contribute a datastet. However, the data is not accessible to use, the event spatial resolution is far larger than camera resolution, and you only show a part of test set. So long a time get no reply.

**Comment by wefvdge** [comment]
do you know how to resolve this?thank you

**Comment by DachunKai** [comment]
> do you know how to resolve this?thank you

不，我也没有解决。曾经有次邮件原作者回我“这么做是为了节省显存，所以把float64转到int型”，所以试着在原很大的数据上x y除以64，但得到的结果仍然挺大的。大于原相机分辨率。后来就没有用了。

**Comment by wefvdge** [comment]
> > do you know how to resolve this?thank you
> 
> 不，我也没有解决。曾经有次邮件原作者回我“这么做是为了节省显存，所以把float64转到int型”，所以试着在原很大的数据上x y除以64，但得到的结果仍然挺大的。大于原相机分辨率。后来就没有用了。

不好意思 好像明白了 我试试

**Comment by wefvdge** [comment]
> > do you know how to resolve this?thank you
> 
> 不，我也没有解决。曾经有次邮件原作者回我“这么做是为了节省显存，所以把float64转到int型”，所以试着在原很大的数据上x y除以64，但得到的结果仍然挺大的。大于原相机分辨率。后来就没有用了。

x是0-65535 y是32-20000
原图是970*625
我算了下 x应该就是原x/969*65535 y是原y/624*19968+32 这样感觉比较说得通，刚好19968=624*32，打算明天试一下

**Comment by ercanburak** [comment]
Anyone still trying to figure this out can also check the code in [EVREAL tools](https://github.com/ercanburak/EVREAL/tree/main/tools). Here, we scale the x and y coordinates of events to the correct range and fix overflow issues. After that conversion, the visualizations of events align with the images (at least to a certain degree.)
